name: package-analyzer-build

on: [push] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Build - GraphBuilder
      run: dotnet build  GraphBuilder/GraphBuilder.sln -c Release
    - name: Test - GraphBuilder 
      run: dotnet test GraphBuilder/tests/tests.csproj -c Release -v m

    - name: Build - PackageHasher
      run: dotnet build  PackageHasher/PackageHasher.sln -c Release
    - name: Test - PackageHasher 
      run: dotnet test PackageHasher/tests/tests.csproj -c Release -v m

    - name: Build - PackageBuilder
      run: dotnet build  PackageBuilder/PackageBuilder.sln -c Release
    - name: Test - PackageBuilder 
      run: dotnet test PackageBuilder/tests/tests.csproj -c Release -v m

    - name: Build - ConsoleTest
      run: dotnet build  ConsoleTest/ConsoleTest.sln -c Release
