name: package-analyzer-build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build - GraphBuilder
      run: dotnet build  GraphBuilder/GraphBuilder.sln -c Release
    - name: Test - GraphBuilder 
      run: dotnet test GraphBuilder/tests/tests.csproj -c Release -v m

    - name: Build - PackageHasher
      run: dotnet build  PackageHasher/PackageHasher.sln -c Release
    - name: Test - PackageHasher 
      run: dotnet test PackageHasher/tests/tests.csproj -c Release -v m

    - name: Build - PackageBuilder
      run: dotnet build  PackageBuilder/PackageBuilder.sln -c Release
    - name: Test - PackageBuilder 
      run: dotnet test PackageBuilder/tests/tests.csproj -c Release -v m

    - name: Build - ConsoleTest
      run: dotnet build  ConsoleTest/ConsoleTest.sln -c Release
