name: update-markdown

on:
  workflow_run:
    workflows:
      - package-analyzer-build
    types: 
      - completed

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
#      with:
#        ref: ${{ github.event.workflow_run.head_branch }}
#    - run: git branch

    - name: Run Autodocs
      uses: dineshsonachalam/markdown-autodocs@v1.0.4
      with:
        output_file_paths: '[./README.md]'
        categories: '[code-block]'